version: '3.8'

  backend:
    build: ./backend
    # Ensure the directory for the DB exists before migration
    command: sh -c "mkdir -p /app/data && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    expose:
      - 8000
    environment:
      - DEBUG=0
      - SQLITE_DB_PATH=/app/data/db.sqlite3
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - ALLOWED_HOSTS=*
      # Add valid secret key for production
      - SECRET_KEY=django-insecure-change-me-in-prod
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    restart: always

volumes:
  static_volume:
  media_volume:
  sqlite_data:
